language: node_js
node_js: node
branch:
  only:
  - master
  - production
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: L1hXusPJ91ColZakfFfvbn8xHNbNsLN92GhrTiBoRhLpwF6aja5fP2wgHYN+I0p82Ul5cIs2bPVmu65L4X6TeVh+cZYcfGs1N50ZYPZKHFV4S8+5AUdlcKEevsMA5F/cQYDh1ME2f0clZcYXgO4V9O6Cy76MI34BV0aM7jcMbu5o3sxaSNrGpkpYdK3pipnJhVrEwS2G8Ctb4wHHfzT3mxVKWGPzK7BkGSYZ7xlF1LNgHBg7EPNzakvHPs3vdrtlMxmuC8T1TuaHOmnDLhtvBbXtOs457FpJtyuqJwRkEmzmqCRMYgEWJw1X5xJiBjBLQZ3kQd5pmT1lalZVx7hn1lsqINzR67TJGb4AKvtJVVq/sjogCYzmOZnxLg/jTRobfon/Elk+ThQI8UJnUWJdDt2pqppSPrHsfaT9MCvDbkiSOVVO1Jmo5R3/xQ4GM7VKdcFFuhLhwc7U/97+Hg52RaC8NX4sybZ+NHWdaDT1AKmJPnBU0qD0DnUzrz34cjCc+Khlpyjm6UNLyMN7wcV14SlYmEmuDcOPwAtOOZinkIGRggozWpl/c7/IrPgrrNoRhcJ0CHPE9mj7eJ/2JdlN3LZyBtWKXQSkzEzL5A6EiaLQT79I8mZwMhY6F2wE/8Bkjb0+GMzOG0ImFZASt+Y8l7vmB+AXpK/l/NLyb7e4/7s=
  keep-history: true
  local-dir: dist
  on:
    branch: production
