[build.environment]
  GCAL_CLIENT_ID="82930465455-k6kn9ll0frlduqj6jegvn92h8opupu02.apps.googleusercontent.com"
  GCAL_API_KEY="AIzaSyDsrNBeibXiHk6iXXQpn_qDs3zRqQNWRmw"

[context.production.environment]
  GCAL_CLIENT_ID="82930465455-k6kn9ll0frlduqj6jegvn92h8opupu02.apps.googleusercontent.com"
  GCAL_API_KEY="AIzaSyDsrNBeibXiHk6iXXQpn_qDs3zRqQNWRmw"
